#!/bin/bash

echo "════════════════════════════════════════════════════════════"
echo "  CORRIGIR ERRO pet_id EM PRODUÇÃO"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Execute este comando no servidor de produção:"
echo ""
echo "sudo mysql clinica_veterinaria < /home/u199209817/domains/systemhomepet.com/public_html/migrations/add_pet_id_to_venda.sql"
echo ""
echo "OU execute manualmente no MySQL:"
echo ""
echo "ALTER TABLE venda ADD COLUMN pet_id INT NULL AFTER observacao;"
echo "ALTER TABLE venda ADD INDEX idx_venda_pet_id (pet_id);"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Depois de executar:"
echo "1. Limpe o cache: php bin/console cache:clear --env=prod"
echo "2. Teste a página: https://systemhomepet.com/clinica/pdv/listar"
echo ""
echo "════════════════════════════════════════════════════════════"
