-- Altera colunas da tabela produto para permitir valores NULL

ALTER TABLE produto 
    MODIFY COLUMN ncm INT DEFAULT NULL,
    MODIFY COLUMN cfop INT DEFAULT NULL,
    MODIFY COLUMN cest INT DEFAULT NULL,
    MODIFY COLUMN codigo_fabrica VARCHAR(255) DEFAULT NULL,
    MODIFY COLUMN data_validade DATETIME DEFAULT NULL,
    MODIFY COLUMN aliquota_icms DOUBLE PRECISION DEFAULT NULL,
    MODIFY COLUMN aliquota_pis DOUBLE PRECISION DEFAULT NULL,
    MODIFY COLUMN aliquota_cofins DOUBLE PRECISION DEFAULT NULL,
    MODIFY COLUMN aliquota_ipi DOUBLE PRECISION DEFAULT NULL,
    MODIFY COLUMN aliquota_iss DOUBLE PRECISION DEFAULT NULL,
    MODIFY COLUMN aliquota_ibs DOUBLE PRECISION DEFAULT NULL,
    MODIFY COLUMN aliquota_cbs DOUBLE PRECISION DEFAULT NULL;
