#index:
#    path: /
#    controller: App\Controller\DefaultController::index
servico_index:
    path: /servico
    controller: App\Controller\ServicoController::index

servico_novo:
    path: /servico/novo
    controller: App\Controller\ServicoController::novo

servico_editar:
    path: /servico/editar/{id}
    controller: App\Controller\ServicoController::editar

servico_deletar:
    path: /servico/deletar/{id}
    controller: App\Controller\ServicoController::deletar
    methods: POST

cliente_index:
    path: /cliente
    controller: App\Controller\ClienteController::index

cliente_novo:
    path: /cliente/novo
    controller: App\Controller\ClienteController::novo

cliente_editar:
    path: /cliente/editar/{id}
    controller: App\Controller\ClienteController::editar

cliente_deletar:
    path: /cliente/deletar/{id}
    controller: App\Controller\ClienteController::deletar
    methods: POST

pet_index:
    path: /pet
    controller: App\Controller\PetController::index

pet_novo:
    path: /pet/novo
    controller: App\Controller\PetController::novo

pet_editar:
    path: /pet/editar/{id}
    controller: App\Controller\PetController::editar

pet_deletar:
    path: /pet/deletar/{id}
    controller: App\Controller\PetController::deletar
    methods: POST

financeiro_relatorio:
    path: /financeiro/relatorio
    controller: App\Controller\FinanceiroController::relatorio
